create database videotienda;
use videotienda;

--CREAMOS LA TABLA DOMINIOS
create table dominios(
TIPO_DOMINIO VARCHAR(30),
ID_DOMINIO VARCHAR(10),
VLR_DOMINIO VARCHAR(50) NOT NULL

PRIMARY KEY(TIPO_DOMINIO, ID_DOMINIO),

)

--CREAMOS LA TABLA PERSONA
create table personas(
NRO_DOC NUMERIC(11) PRIMARY KEY,
TIPO_DOC VARCHAR(3) NOT NULL,
NOMBRES VARCHAR(50) NOT NULL,
CELULAR NUMERIC(11) NOT NULL,
CORREO VARCHAR(100) NOT NULL,
DIRECCION VARCHAR(100) NOT NULL,
TIPO_PERSONA VARCHAR(3) NOT NULL,
CONTRASENA VARCHAR(10)
) 

--CREAMOS LA TABLA CATEGORIAS
create table categorias(
ID_CATEGORIA NUMERIC(11) PRIMARY KEY,
NOM_CATEGORIA VARCHAR(50) NOT NULL
)

--CREAMOS LA TABLA PRODUCTORES
create table productores(
ID_PROD NUMERIC(11) PRIMARY KEY,
NOM_PROD VARCHAR(50) NOT NULL
)

--CREAMOS LA TABLA VIDEOJUEGOS
create table videojuegos(
NRO_REFERENCIA NUMERIC(11) PRIMARY KEY,
NOM_VIDEOJUEGO VARCHAR(50) NOT NULL,
IMG_VIDEOJUEGO VARCHAR(100),
ID_PROD NUMERIC(11)

FOREIGN KEY (ID_PROD) REFERENCES productores
)

--CREAMOS LA TABLA CAT-VIDEOJUEGOS
create table cat_videojuegos(
ID_CAT_VIDEOJUEGOS NUMERIC(11) PRIMARY KEY,
ID_CATEGORIA NUMERIC(11),
NRO_REFERENCIA NUMERIC(11)

FOREIGN KEY (ID_CATEGORIA) REFERENCES categorias,
FOREIGN KEY (NRO_REFERENCIA) REFERENCES videojuegos
)

--CREAMOS LA TABLA ALQUILER
create table alquiler(
ID_ALQUILER NUMERIC(11) PRIMARY KEY,
FEC_ALQUILER DATETIME NOT NULL,
FEC_DEVOLUCION DATETIME NOT NULL,
VLR_ALQUILER DECIMAL(5,0) NOT NULL,
VLR_MULTAS DECIMAL(5,0),
NRO_DOC NUMERIC(11)

FOREIGN KEY (NRO_DOC) REFERENCES personas
)


--CREAMOS LA TABLA ALQ-VIDEOJUEGOS
create table alq_videojuegos(
ID_ALQ_VIDEOJUEGOS NUMERIC(11) PRIMARY KEY,
ID_ALQUILER NUMERIC(11),
NRO_REFERENCIA NUMERIC(11)

FOREIGN KEY (ID_ALQUILER) REFERENCES alquiler,
FOREIGN KEY (NRO_REFERENCIA) REFERENCES videojuegos
)
